### ISSUE TITLE
Proposal: rename to "mallard"

### ISSUE THREAD

**Issue by krancour** [lovethedrake/devdrake#45]
The DevDrake binary is called `drake` because `devdrake` doesn't feel as nice to type. This could make people (ourselves included) refer to _this implementation of the spec_ as "drake," leading to ambiguity as to whether one is referring to this tool or the spec itself.

This could be solved by simply coming up with a better name.

I propose sticking with the duck theme and calling this tool "mallard".

**Comment by carolynvs** [comment]
lol, I am already imagining a page with a list of implementations of drake, all with cute duck pictures.

be warned that I would immediately alias mallard to `m` so that I didn't have to mistype it repeatedly. 😀

**Comment by krancour** [comment]
Same.
